run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - canonicalheader
  - contextcheck
  - errcheck
  - goconst
  - gocritic
  - godot
  - goimports
  - gomoddirectives
  - gomodguard
  - gosimple
  - govet
  - ineffassign
  - nilerr
  - nilnil
  - paralleltest
  - staticcheck
  - tenv
  - testifylint
  - unconvert
  - unused
  - wsl
  - zerologlint

linters-settings:
  gocritic:
    # Which checks should be disabled; can't be combined with 'enabled-checks'.
    # Default: []
    disabled-checks:
    - exitAfterDefer
